# bot/ai_service.py
import os
from typing import Optional, Dict, Any
import aiohttp
import json

# OpenAI API configuration
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4o-mini")  # Default to cost-effective model


async def generate_ai_solution(task: Dict[str, Any]) -> str:
    """
    Generate AI-powered solution explanation for a math task.
    
    Args:
        task: Dictionary containing task information (task_text, image_path, correct_option, etc.)
    
    Returns:
        AI-generated solution explanation in Markdown/LaTeX format
    
    Raises:
        ValueError: If API key is not configured
        Exception: If API request fails
    """
    if not OPENAI_API_KEY:
        raise ValueError("OPENAI_API_KEY environment variable is not set")
    
    # Build the prompt for the AI
    prompt = _build_solution_prompt(task)
    
    # Call OpenAI API
    async with aiohttp.ClientSession() as session:
        headers = {
            "Authorization": f"Bearer {OPENAI_API_KEY}",
            "Content-Type": "application/json"
        }
        
        payload = {
            "model": OPENAI_MODEL,
            "messages": [
                {
                    "role": "system",
                    "content": (
                        "Сіз математикалық есептерді шешетін ұстазсыз. "
                        "Есепті толық және түсінікті түрде түсіндіріңіз. "
                        "Жауапты қазақ тілінде беріңіз. "
                        "LaTeX формулаларын қолданыңыз (inline: $формула$, block: $$формула$$). "
                        "Шешім қадам-қадаммен, нақты және оқуға оңай болуы керек."
                    )
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            "temperature": 0.7,
            "max_tokens": 1500
        }
        
        async with session.post(
            "https://api.openai.com/v1/chat/completions",
            headers=headers,
            json=payload,
            timeout=aiohttp.ClientTimeout(total=60)
        ) as response:
            if response.status != 200:
                error_text = await response.text()
                raise Exception(f"OpenAI API error (status {response.status}): {error_text}")
            
            result = await response.json()
            
            # Extract the generated solution
            if "choices" in result and len(result["choices"]) > 0:
                solution = result["choices"][0]["message"]["content"]
                return solution.strip()
            else:
                raise Exception("No solution generated by AI")


def _build_solution_prompt(task: Dict[str, Any]) -> str:
    """Build a prompt for AI to generate solution explanation."""
    prompt_parts = []
    
    # Add task text if available
    if task.get("task_text"):
        prompt_parts.append(f"**Есеп:**\n{task['task_text']}")
    else:
        prompt_parts.append("**Есеп:** (суретте берілген)")
    
    # Add answer type
    answer_type = task.get("answer_type", "quiz")
    if answer_type == "quiz":
        prompt_parts.append("\n**Түрі:** Тест (A/B/C/D)")
        
        # Add quiz options if available
        options = []
        for opt in ['a', 'b', 'c', 'd']:
            opt_text = task.get(f"option_{opt}_text")
            if opt_text:
                options.append(f"{opt.upper()}) {opt_text}")
        
        if options:
            prompt_parts.append("\n**Нұсқалар:**")
            prompt_parts.extend(options)
    else:
        prompt_parts.append("\n**Түрі:** Қолмен енгізу")
    
    # Add correct answer
    correct = task.get("correct_option", "")
    if answer_type == "quiz":
        prompt_parts.append(f"\n**Дұрыс жауап:** {correct}")
    else:
        prompt_parts.append(f"\n**Дұрыс жауап:** {correct}")
    
    # Add instruction
    prompt_parts.append(
        "\n\nБұл есептің толық шешімін қадам-қадаммен түсіндіріп беріңіз. "
        "Шешім қазақ тілінде, математикалық формулалар LaTeX форматында болуы керек."
    )
    
    return "\n".join(prompt_parts)
